"""
License Service — one-time-activation-key licensing, now backed by the
local `licenses` table (see app.models.models.License) instead of a
separate license server. That server (license app/) is retired; its
generate/validate/revoke logic now lives here and in
app/api/routes/admin.py, both running inside this same backend/process.

A company activates ONCE with a key like AICAL-XXXX-XXXX-XXXX-XXXX
(generated by an admin via POST /api/v1/admin/generate or the admin.html
panel), and the key stays valid until `expires_at` (1 year by default).

Flow:
  1. POST /api/v1/license/activate  → validates + activates against the
     local `licenses` table, stores license_key/tier/expires_at/domain on
     the Company row. Also used directly during self-registration (see
     app/api/routes/auth.py's /register), so a new customer's license key
     activates in the same step as creating their account.
  2. On backend startup, and every 24h via Celery beat, revalidate and
     cache the result in Redis so the call-gate check in tasks.py doesn't
     hit the DB on every single outbound call.
  3. Because this is now a local DB read instead of a network call, the
     "server unreachable, fail open" path below is mostly dead code in
     practice — but it's left in place as a safety net (e.g. a transient
     DB connection blip shouldn't lock out a live campaign either).
"""
import logging
import secrets
import string
from datetime import datetime, timedelta
from typing import Any, Dict, Optional

from sqlalchemy import select

from app.core.config import settings

logger = logging.getLogger(__name__)

CACHE_TTL_SECONDS = 26 * 3600   # a little over 24h — outlives the beat interval

TIER_LIMITS = {
    "starter":    {"max_leads": 1000,   "max_calls_month": 500,   "price_usd": 299},
    "pro":        {"max_leads": 10000,  "max_calls_month": 5000,  "price_usd": 499},
    "enterprise": {"max_leads": 999999, "max_calls_month": 99999, "price_usd": 999},
}


def generate_key() -> str:
    chars = string.ascii_uppercase + string.digits
    parts = ["".join(secrets.choice(chars) for _ in range(6)) for _ in range(4)]
    return "AICAL-" + "-".join(parts)


def _cache_key(company_id: str) -> str:
    return f"license_status:{company_id}"


async def activate(license_key: str, domain: str) -> Dict[str, Any]:
    """Activates a license key against the local `licenses` table. Mirrors
    the old license server's /activate response shape so callers
    (app/api/routes/license.py, app/api/routes/auth.py) don't need to
    change."""
    from app.core.database import AsyncSessionLocal
    from app.models.models import License

    async with AsyncSessionLocal() as db:
        lic = await db.get(License, license_key)
        if not lic:
            return {"success": False, "error": "License key not found"}
        if lic.status == "revoked":
            return {"success": False, "error": "License has been revoked"}
        if lic.domain and lic.domain != domain:
            return {"success": False, "error": f"License already activated for domain: {lic.domain}"}
        if lic.expires_at and datetime.utcnow() > lic.expires_at:
            return {"success": False, "error": "License has expired"}

        lic.domain       = domain
        lic.activated_at = datetime.utcnow()
        lic.status        = "active"
        await db.commit()

        return {
            "success":     True,
            "license_key": license_key,
            "domain":      domain,
            "expires_at":  lic.expires_at.isoformat() if lic.expires_at else None,
            "tier":        lic.tier,
        }


async def validate(license_key: str, domain: str) -> Dict[str, Any]:
    """Validates a license key against the local `licenses` table. Never
    raises — returns {"valid": False, "message": "..."} on any failure so
    callers can decide whether to fail open or closed."""
    if not license_key:
        return {"valid": False, "message": "No license key configured"}

    from app.core.database import AsyncSessionLocal
    from app.models.models import License

    try:
        async with AsyncSessionLocal() as db:
            lic = await db.get(License, license_key)
            if not lic:
                return {"valid": False, "message": "License key not found"}
            if lic.status == "revoked":
                return {"valid": False, "message": "License has been revoked"}
            if lic.status != "active":
                return {"valid": False, "message": "License not yet activated. Call /activate first."}

            registered_domain = lic.domain or ""
            if registered_domain and domain not in ("localhost", "127.0.0.1", registered_domain):
                return {"valid": False, "message": f"Domain mismatch. Expected: {registered_domain}"}

            if lic.expires_at and datetime.utcnow() > lic.expires_at:
                return {
                    "valid": False,
                    "expires_at": lic.expires_at.isoformat(),
                    "message": "License expired. Please renew.",
                }

            lic.last_validated_at = datetime.utcnow()
            await db.commit()

            limits = TIER_LIMITS.get(lic.tier or "pro", TIER_LIMITS["pro"])
            return {
                "valid":           True,
                "tier":            lic.tier,
                "client_name":     lic.client_name,
                "expires_at":      lic.expires_at.isoformat() if lic.expires_at else None,
                "max_leads":       limits["max_leads"],
                "max_calls_month": limits["max_calls_month"],
                "message":         "License valid",
            }
    except Exception as e:
        logger.warning(f"License validate() DB error: {e}")
        return {"valid": None, "message": f"License check temporarily unavailable: {e}"}


async def refresh_status(company) -> Dict[str, Any]:
    """Revalidates a Company's license against the license server and
    caches the outcome in Redis. `company` is the Company ORM row.

    IMPORTANT: this only ever writes company.license_status to the DB when
    the license server gave a definitive answer (valid True or explicitly
    False). If the server is merely unreachable (network blip, not started
    yet, wrong URL, DNS hiccup), we must NOT flip an already-activated
    company to "inactive" — that would lock a paying customer out over a
    transient issue, which is exactly the kind of bug this guards against.
    """
    from app.core.redis_client import redis_client

    if not company or not company.license_key:
        result = {"valid": False, "message": "No license activated", "checked_at": datetime.utcnow().isoformat()}
        if company:
            await redis_client.set(_cache_key(company.id), result, expire=CACHE_TTL_SECONDS)
        return result

    domain = company.license_domain or "localhost"
    result = await validate(company.license_key, domain)

    if result.get("valid") is None:
        # Server unreachable — fail open. Keep whatever was cached before,
        # and do NOT touch the Company row at all: an already-active
        # license stays active in the DB until we get a real answer.
        cached = await redis_client.get(_cache_key(company.id))
        if cached:
            return cached
        # No prior cache either (e.g. right after activation, before the
        # first successful check) — report "unknown", not "invalid". The
        # caller falls back to the locally-stored license_status either way.
        return {
            "valid": None,
            "message": result.get("message", "License server unreachable — using last known status"),
            "checked_at": datetime.utcnow().isoformat(),
        }

    # From here on we have a definitive answer from the license server.
    result["checked_at"] = datetime.utcnow().isoformat()
    await redis_client.set(_cache_key(company.id), result, expire=CACHE_TTL_SECONDS)

    # Mirror the key fields onto the Company row so /license/status can
    # answer instantly without a live round trip (see app/api/routes/license.py).
    try:
        from app.core.database import AsyncSessionLocal
        async with AsyncSessionLocal() as db:
            row = await db.get(type(company), company.id)
            if row:
                row.license_status     = "active" if result.get("valid") else "inactive"
                row.license_tier       = result.get("tier") or row.license_tier
                row.license_expires_at = _parse_dt(result.get("expires_at")) or row.license_expires_at
                await db.commit()
    except Exception as e:
        logger.debug(f"License status mirror-to-DB skipped: {e}")

    return result


async def get_cached_status(company_id: str) -> Optional[Dict[str, Any]]:
    from app.core.redis_client import redis_client
    return await redis_client.get(_cache_key(company_id))


async def is_call_allowed(company) -> tuple:
    """Returns (allowed: bool, reason: str) — used as the call-gate check
    in tasks.py, replacing the old Firestore minutes-remaining gate."""
    if not company or not company.license_key:
        return False, "no license activated — add your activation key in Settings"

    cached = await get_cached_status(company.id)
    if not cached:
        cached = await refresh_status(company)

    if cached.get("valid") is False:
        return False, cached.get("message", "license invalid or expired")

    expires_at = _parse_dt(cached.get("expires_at")) or company.license_expires_at
    if expires_at and datetime.utcnow() > expires_at:
        return False, "license expired — please renew your activation key"

    return True, "ok"


def _parse_dt(iso_str: Optional[str]):
    if not iso_str:
        return None
    try:
        return datetime.fromisoformat(iso_str.replace("Z", "+00:00")).replace(tzinfo=None)
    except Exception:
        return None
