"""cashfree plan system replaces license

Revision ID: 1e4e5987ba49
Revises: afa89ef87873
Create Date: 2026-08-14 01:59:27.529434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Needed because autogenerate references custom column types (e.g.
# EncryptedString on Company.vobiz_auth_id/vobiz_auth_token) by their
# fully-qualified name.
import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = '1e4e5987ba49'
down_revision: Union[str, None] = 'afa89ef87873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('cf_order_id', sa.String(), nullable=False),
    sa.Column('cf_cf_order_id', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('rate_per_minute', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_session_id', sa.String(), nullable=True),
    sa.Column('raw_create_response', sa.JSON(), nullable=True),
    sa.Column('raw_webhook_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_cf_order_id'), 'payment_orders', ['cf_order_id'], unique=True)
    # server_default on every new NOT-effectively-nullable column below —
    # autogenerate leaves these nullable=True (SQLite/most DBs can't add a
    # NOT NULL column to a populated table without a default in the same
    # statement), but WITHOUT a server_default every existing row would get
    # NULL instead of the same value new rows get from the ORM's
    # `default=` — e.g. every call ever logged before this migration would
    # read channel=NULL instead of channel="ai", which breaks the AI/Human
    # Call Log tab split for 100% of historical calls.
    op.add_column('batches', sa.Column('agent_type', sa.String(), nullable=False, server_default='ai'))
    op.add_column('call_logs', sa.Column('channel', sa.String(), nullable=False, server_default='ai'))
    op.add_column('call_logs', sa.Column('dialed_by', sa.String(), nullable=True))
    # batch_alter_table — SQLite can't ALTER to add a constraint directly
    # (no ALTER TABLE ADD CONSTRAINT support); batch mode does the
    # standard SQLite copy-and-move under the hood. Works unchanged on
    # Postgres/Neon too (falls straight through to a plain ALTER there).
    with op.batch_alter_table('call_logs') as batch_op:
        batch_op.create_foreign_key('fk_call_logs_dialed_by_users', 'users', ['dialed_by'], ['id'])
    # is_demo_account / demo_calls_remaining: pre-existing gap between
    # models.py and the initial migration (unrelated to this change, just
    # caught by autogenerate while diffing) — added here since they were
    # never actually in the DB.
    op.add_column('companies', sa.Column('is_demo_account', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('companies', sa.Column('demo_calls_remaining', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('plan_type', sa.String(), nullable=False, server_default='none'))
    op.add_column('companies', sa.Column('plan_minutes_total', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('plan_rate_per_minute', sa.Float(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('plan_amount_paid', sa.Float(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('plan_purchased_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('plan_minutes_used', sa.Float(), nullable=False, server_default='0'))
    op.add_column('companies', sa.Column('trial_used', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_column('companies', 'license_key')
    op.drop_column('companies', 'license_domain')
    op.drop_column('companies', 'license_expires_at')
    op.drop_column('companies', 'license_tier')
    op.drop_column('companies', 'license_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('license_status', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('license_tier', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('license_expires_at', sa.DATETIME(), nullable=True))
    op.add_column('companies', sa.Column('license_domain', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('license_key', sa.VARCHAR(), nullable=True))
    op.drop_column('companies', 'trial_used')
    op.drop_column('companies', 'plan_minutes_used')
    op.drop_column('companies', 'plan_expires_at')
    op.drop_column('companies', 'plan_purchased_at')
    op.drop_column('companies', 'plan_amount_paid')
    op.drop_column('companies', 'plan_rate_per_minute')
    op.drop_column('companies', 'plan_minutes_total')
    op.drop_column('companies', 'plan_type')
    op.drop_column('companies', 'demo_calls_remaining')
    op.drop_column('companies', 'is_demo_account')
    with op.batch_alter_table('call_logs') as batch_op:
        batch_op.drop_constraint('fk_call_logs_dialed_by_users', type_='foreignkey')
    op.drop_column('call_logs', 'dialed_by')
    op.drop_column('call_logs', 'channel')
    op.drop_column('batches', 'agent_type')
    op.drop_index(op.f('ix_payment_orders_cf_order_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    # ### end Alembic commands ###
