"""initial schema

Revision ID:afa89ef87873
Revises: 
Create Date: 2026-07-27 06:26:20.352187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = 'afa89ef87873'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('faqs', sa.Text(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('description_hi', sa.Text(), nullable=True),
    sa.Column('services_hi', sa.Text(), nullable=True),
    sa.Column('faqs_hi', sa.Text(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('active_product', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('voice_language', sa.String(), nullable=True),
    sa.Column('voice_gender', sa.String(), nullable=True),
    sa.Column('tts_provider', sa.String(), nullable=True),
    sa.Column('tts_voice', sa.String(), nullable=True),
    sa.Column('inbound_system_prompt', sa.Text(), nullable=True),
    sa.Column('outbound_sales_prompt', sa.Text(), nullable=True),
    sa.Column('greeting_inbound', sa.Text(), nullable=True),
    sa.Column('greeting_outbound', sa.Text(), nullable=True),
    sa.Column('greeting_inbound_hi', sa.Text(), nullable=True),
    sa.Column('greeting_outbound_hi', sa.Text(), nullable=True),
    sa.Column('forward_number', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('vobiz_auth_id', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('vobiz_auth_token', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('vobiz_phone_number', sa.String(), nullable=True),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('license_domain', sa.String(), nullable=True),
    sa.Column('license_tier', sa.String(), nullable=True),
    sa.Column('license_status', sa.String(), nullable=True),
    sa.Column('license_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_from_address', sa.String(), nullable=True),
    sa.Column('email_from_name', sa.String(), nullable=True),
    sa.Column('email_reply_to', sa.String(), nullable=True),
    sa.Column('email_signature', sa.Text(), nullable=True),
    sa.Column('vector_collection_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('batch_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('filter_criteria', sa.JSON(), nullable=True),
    sa.Column('lead_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('leads_processed', sa.Integer(), nullable=True),
    sa.Column('leads_succeeded', sa.Integer(), nullable=True),
    sa.Column('leads_failed', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('product_focus', sa.String(), nullable=True),
    sa.Column('call_mode', sa.String(), nullable=True),
    sa.Column('email_subject_template', sa.String(), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('interest_level', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('key_info', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_question', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('call_attempts', sa.Integer(), nullable=True),
    sa.Column('last_called_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_call_at', sa.DateTime(), nullable=True),
    sa.Column('email_status', sa.String(), nullable=True),
    sa.Column('email_attempts', sa.Integer(), nullable=True),
    sa.Column('last_emailed_at', sa.DateTime(), nullable=True),
    sa.Column('email_opt_out', sa.Boolean(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('call_control_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('lead_status_after', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('transferred_to_human', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_call_control_id'), 'call_logs', ['call_control_id'], unique=True)
    op.create_table('email_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('to_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=True),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sendgrid_message_id', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('reply_body', sa.Text(), nullable=True),
    sa.Column('reply_status', sa.String(), nullable=True),
    sa.Column('ai_reply_draft', sa.Text(), nullable=True),
    sa.Column('ai_reply_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reply_sent', sa.Boolean(), nullable=True),
    sa.Column('ai_reply_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reply_sentiment', sa.String(), nullable=True),
    sa.Column('reply_intent', sa.String(), nullable=True),
    sa.Column('email_thread', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('window_start_time', sa.String(), nullable=True),
    sa.Column('window_end_time', sa.String(), nullable=True),
    sa.Column('base_timezone', sa.String(), nullable=True),
    sa.Column('use_lead_timezone', sa.Boolean(), nullable=True),
    sa.Column('allowed_days', sa.JSON(), nullable=True),
    sa.Column('max_per_hour', sa.Integer(), nullable=True),
    sa.Column('delay_between_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_call_logs_call_control_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_table('batch_leads')
    op.drop_table('leads')
    op.drop_table('knowledge_documents')
    op.drop_table('batches')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('licenses')
    # ### end Alembic commands ###
