"""firebase auth

Revision ID: d9defb85bf92
Revises: 1e4e5987ba49
Create Date: 2026-08-16 16:32:43.067925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Needed because autogenerate references custom column types (e.g.
# EncryptedString on Company.vobiz_auth_id/vobiz_auth_token) by their
# fully-qualified name.
import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = 'd9defb85bf92'
down_revision: Union[str, None] = '1e4e5987ba49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(), nullable=True))
    # batch_alter_table — SQLite has no ALTER COLUMN; batch mode does the
    # standard SQLite copy-and-move under the hood. Runs as a plain ALTER
    # on Postgres/Neon unchanged (same reasoning as the previous
    # migration's dialed_by foreign key).
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    # NOTE: downgrading requires every existing row to already have a
    # hashed_password — any user who signed up post-Firebase-switch has
    # NULL here and this will fail (correctly) rather than silently
    # leave them with an unusable/empty password hash. Backfill or
    # delete those rows first if you actually need to roll back.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
